<?php

/**
 * CondeConverter is a simple straight forward class for converting
 * ISO 639 Languages Codes or ISO Alpha Country codes from 2 to 3 digits
 * or vice versa. For more info see https://github.com/sugarfixx/LanguageTools
 *
 * @category helper
 * @author Sugarfixx
 * @copyright 28.10.2016
 * @license  MIT
 * @version Release: 1.0
 *
 * @method public function convertLanguageCode($tag, $format = 'lowercase', $option = 'T')
 * @method public function convertCountryCode($tag, $format = 'lowercase')
 * @method private function iso2to3($tag, $format, $option)
 * @method private function iso3to2($tag, $format, $option)
 * @method private function alpha3to2($tag, $format)
 * @method private function alpha2to3($tag, $format)
 * @method private function returnFormated($value, $format)
 * @method private function iso2digit_T()
 * @method private function iso2digit_T()
 * @method private function iso3digit_T()
 * @method private function iso3digit_T()
 * @method private function alpha3digit()
 * @method private function alpha3digit()
 */

class ISOCodeConverter
{
    /**
     * Convert ISO 639 formated language codes auto detects if input is 2 or 3 digit
     * @param $tag string
     * @param $format string
     * @param $option sets T or B
     * @return method
     */
    public function convertLanguageCode($tag, $format = FALSE, $option = FALSE )
    {
        $variant = ($option !== TRUE ? 'T' : 'B');
        if (strlen(trim($tag)) == 2 ) {
            return $this->iso2to3(trim($tag), $format, $variant );
        } elseif (strlen(trim($tag)) == 3) {
            return $this->iso3to2(trim($tag), $format, $variant);
        }
        return $tag.' is not a valid Language tag.';
    }

    /**
     * Converts ISO Alpha country codes auto detects if input is 2 or 3 digits
     * @param $tag string
     * @param $format string
     * @return method
     */
    public function convertCountryCode($tag, $format = FALSE)
    {
        if (strlen(trim($tag)) == 2) {
            return $this->alpha2to3(trim($tag),$format, $option);
        } elseif (strlen(trim($tag)) == 3) {
            return $this->alpha3to2(trim($tag),$format, $option);
        }
        return $tag.' is not a valid Country tag.';
    }

    /**
     * Finds ISO 639-1 formated language code and return the appropriate ISO 639-2/T or ISO 639-2/B code
     * @param $tag string
     * @param $format string
     * @param $option sets T or B
     * @return method
     */
    private function iso2to3($tag, $format, $option)
    {
        $method = 'iso2digit_'.$option;
        $dictionary = $this->{$method}();
        $value = $dictionary[strtolower($tag)];
        return $this->returnFormated($value, $format);
    }

    /**
     * Finds ISO 639-2/T ISO 639-2/B formated language code and return the appropriate ISO 639-1 code
     * @param $tag string
     * @param $format string
     * @param $option sets T or B
     * @return method
     */
    private function iso3to2($tag, $format, $option)
    {
        $method = 'iso3digit_'.$option;
        $dictionary = $this->{$method}();
        $value = $dictionary[strtolower($tag)];
        return $this->returnFormated($value, $format);
    }

    /**
     * Finds Alpha 3 formated country code and return the appropriate Alpha 2 code
     * @param $tag string
     * @param $format string
     * @return method
     */
    private function alpha3to2($tag, $format)
    {
        $dictionary = $this->alpha3digit();
        $value = $dictionary[strtolower($tag)];
        return $this->returnFormated($value, $format);
    }

    /**
     * Finds Alpha 2 formated country code and return the appropriate Alpha 3 code
     * @param $tag string
     * @param $format string
     * @return method
     */
    private function alpha2to3($tag, $format)
    {
        $dictionary = $this->alpha2digit();
        $value = $dictionary[strtolower($tag)];
        return $this->returnFormated($value, $format);
    }

    /**
     * Return result value string woth correct format
     * @param $value string
     * @param $format string
     * @return strtoupper||strtolower
     */
    private function returnFormated($value, $format)
    {
        return ($format !== TRUE ? strtolower($value) : strtoupper($value));
    }

    /**
     * @return array
     */
    private function iso2digit_T()
    {
        return [
            'ab' => 'abk',
            'aa' => 'aar',
            'af' => 'afr',
            'ak' => 'aka',
            'sq' => 'sqi',
            'am' => 'amh',
            'ar' => 'ara',
            'an' => 'arg',
            'hy' => 'hye',
            'as' => 'asm',
            'av' => 'ava',
            'ae' => 'ave',
            'ay' => 'aym',
            'az' => 'aze',
            'bm' => 'bam',
            'ba' => 'bak',
            'eu' => 'eus',
            'be' => 'bel',
            'bn' => 'ben',
            'bh' => 'bih',
            'bi' => 'bis',
            'bs' => 'bos',
            'br' => 'bre',
            'bg' => 'bul',
            'my' => 'mya',
            'ca' => 'cat',
            'ch' => 'cha',
            'ce' => 'che',
            'ny' => 'nya',
            'zh' => 'zho',
            'cv' => 'chv',
            'kw' => 'cor',
            'co' => 'cos',
            'cr' => 'cre',
            'hr' => 'hrv',
            'cs' => 'ces',
            'da' => 'dan',
            'dv' => 'div',
            'nl' => 'nld',
            'dz' => 'dzo',
            'en' => 'eng',
            'eo' => 'epo',
            'et' => 'est',
            'ee' => 'ewe',
            'fo' => 'fao',
            'fj' => 'fij',
            'fi' => 'fin',
            'fr' => 'fra',
            'ff' => 'ful',
            'gl' => 'glg',
            'ka' => 'kat',
            'de' => 'deu',
            'el' => 'ell',
            'gn' => 'grn',
            'gu' => 'guj',
            'ht' => 'hat',
            'ha' => 'hau',
            'he' => 'heb',
            'hz' => 'her',
            'hi' => 'hin',
            'ho' => 'hmo',
            'hu' => 'hun',
            'ia' => 'ina',
            'id' => 'ind',
            'ie' => 'ile',
            'ga' => 'gle',
            'ig' => 'ibo',
            'ik' => 'ipk',
            'io' => 'ido',
            'is' => 'isl',
            'it' => 'ita',
            'iu' => 'iku',
            'ja' => 'jpn',
            'jv' => 'jav',
            'kl' => 'kal',
            'kn' => 'kan',
            'kr' => 'kau',
            'ks' => 'kas',
            'kk' => 'kaz',
            'km' => 'khm',
            'ki' => 'kik',
            'rw' => 'kin',
            'ky' => 'kir',
            'kv' => 'kom',
            'kg' => 'kon',
            'ko' => 'kor',
            'ku' => 'kur',
            'kj' => 'kua',
            'la' => 'lat',
            'lb' => 'ltz',
            'lg' => 'lug',
            'li' => 'lim',
            'ln' => 'lin',
            'lo' => 'lao',
            'lt' => 'lit',
            'lu' => 'lub',
            'lv' => 'lav',
            'gv' => 'glv',
            'mk' => 'mkd',
            'mg' => 'mlg',
            'ms' => 'msa',
            'ml' => 'mal',
            'mt' => 'mlt',
            'mi' => 'mri',
            'mr' => 'mar',
            'mh' => 'mah',
            'mn' => 'mon',
            'na' => 'nau',
            'nv' => 'nav',
            'nd' => 'nde',
            'ne' => 'nep',
            'ng' => 'ndo',
            'nb' => 'nob',
            'nn' => 'nno',
            'no' => 'nor',
            'ii' => 'iii',
            'nr' => 'nbl',
            'oc' => 'oci',
            'oj' => 'oji',
            'cu' => 'chu',
            'om' => 'orm',
            'or' => 'ori',
            'os' => 'oss',
            'pa' => 'pan',
            'pi' => 'pli',
            'fa' => 'fas',
            'pl' => 'pol',
            'ps' => 'pus',
            'pt' => 'por',
            'qu' => 'que',
            'rm' => 'roh',
            'rn' => 'run',
            'ro' => 'ron',
            'ru' => 'rus',
            'sa' => 'san',
            'sc' => 'srd',
            'sd' => 'snd',
            'se' => 'sme',
            'sm' => 'smo',
            'sg' => 'sag',
            'sr' => 'srp',
            'gd' => 'gla',
            'sn' => 'sna',
            'si' => 'sin',
            'sk' => 'slk',
            'sl' => 'slv',
            'so' => 'som',
            'st' => 'sot',
            'es' => 'spa',
            'su' => 'sun',
            'sw' => 'swa',
            'ss' => 'ssw',
            'sv' => 'swe',
            'ta' => 'tam',
            'te' => 'tel',
            'tg' => 'tgk',
            'th' => 'tha',
            'ti' => 'tir',
            'bo' => 'bod',
            'tk' => 'tuk',
            'tl' => 'tgl',
            'tn' => 'tsn',
            'to' => 'ton',
            'tr' => 'tur',
            'ts' => 'tso',
            'tt' => 'tat',
            'tw' => 'twi',
            'ty' => 'tah',
            'ug' => 'uig',
            'uk' => 'ukr',
            'ur' => 'urd',
            'uz' => 'uzb',
            've' => 'ven',
            'vi' => 'vie',
            'vo' => 'vol',
            'wa' => 'wln',
            'cy' => 'cym',
            'wo' => 'wol',
            'fy' => 'fry',
            'xh' => 'xho',
            'yi' => 'yid',
            'yo' => 'yor',
            'za' => 'zha',
            'zu' => 'zul'
        ];
    }

    /**
     * @return array
     */
    private function iso2digit_B()
    {
        return [
            'ab' => 'abk',
            'aa' => 'aar',
            'af' => 'afr',
            'ak' => 'aka',
            'sq' => 'alb',
            'am' => 'amh',
            'ar' => 'ara',
            'an' => 'arg',
            'hy' => 'arm',
            'as' => 'asm',
            'av' => 'ava',
            'ae' => 'ave',
            'ay' => 'aym',
            'az' => 'aze',
            'bm' => 'bam',
            'ba' => 'bak',
            'eu' => 'baq',
            'be' => 'bel',
            'bn' => 'ben',
            'bh' => 'bih',
            'bi' => 'bis',
            'bs' => 'bos',
            'br' => 'bre',
            'bg' => 'bul',
            'my' => 'bur',
            'ca' => 'cat',
            'ch' => 'cha',
            'ce' => 'che',
            'ny' => 'nya',
            'zh' => 'chi',
            'cv' => 'chv',
            'kw' => 'cor',
            'co' => 'cos',
            'cr' => 'cre',
            'hr' => 'hrv',
            'cs' => 'cze',
            'da' => 'dan',
            'dv' => 'div',
            'nl' => 'dut',
            'dz' => 'dzo',
            'en' => 'eng',
            'eo' => 'epo',
            'et' => 'est',
            'ee' => 'ewe',
            'fo' => 'fao',
            'fj' => 'fij',
            'fi' => 'fin',
            'fr' => 'fre',
            'ff' => 'ful',
            'gl' => 'glg',
            'ka' => 'geo',
            'de' => 'ger',
            'el' => 'gre',
            'gn' => 'grn',
            'gu' => 'guj',
            'ht' => 'hat',
            'ha' => 'hau',
            'he' => 'heb',
            'hz' => 'her',
            'hi' => 'hin',
            'ho' => 'hmo',
            'hu' => 'hun',
            'ia' => 'ina',
            'id' => 'ind',
            'ie' => 'ile',
            'ga' => 'gle',
            'ig' => 'ibo',
            'ik' => 'ipk',
            'io' => 'ido',
            'is' => 'ice',
            'it' => 'ita',
            'iu' => 'iku',
            'ja' => 'jpn',
            'jv' => 'jav',
            'kl' => 'kal',
            'kn' => 'kan',
            'kr' => 'kau',
            'ks' => 'kas',
            'kk' => 'kaz',
            'km' => 'khm',
            'ki' => 'kik',
            'rw' => 'kin',
            'ky' => 'kir',
            'kv' => 'kom',
            'kg' => 'kon',
            'ko' => 'kor',
            'ku' => 'kur',
            'kj' => 'kua',
            'la' => 'lat',
            'lb' => 'ltz',
            'lg' => 'lug',
            'li' => 'lim',
            'ln' => 'lin',
            'lo' => 'lao',
            'lt' => 'lit',
            'lu' => 'lub',
            'lv' => 'lav',
            'gv' => 'glv',
            'mk' => 'mac',
            'mg' => 'mlg',
            'ms' => 'may',
            'ml' => 'mal',
            'mt' => 'mlt',
            'mi' => 'mao',
            'mr' => 'mar',
            'mh' => 'mah',
            'mn' => 'mon',
            'na' => 'nau',
            'nv' => 'nav',
            'nd' => 'nde',
            'ne' => 'nep',
            'ng' => 'ndo',
            'nb' => 'nob',
            'nn' => 'nno',
            'no' => 'nor',
            'ii' => 'iii',
            'nr' => 'nbl',
            'oc' => 'oci',
            'oj' => 'oji',
            'cu' => 'chu',
            'om' => 'orm',
            'or' => 'ori',
            'os' => 'oss',
            'pa' => 'pan',
            'pi' => 'pli',
            'fa' => 'per',
            'pl' => 'pol',
            'ps' => 'pus',
            'pt' => 'por',
            'qu' => 'que',
            'rm' => 'roh',
            'rn' => 'run',
            'ro' => 'rum',
            'ru' => 'rus',
            'sa' => 'san',
            'sc' => 'srd',
            'sd' => 'snd',
            'se' => 'sme',
            'sm' => 'smo',
            'sg' => 'sag',
            'sr' => 'srp',
            'gd' => 'gla',
            'sn' => 'sna',
            'si' => 'sin',
            'sk' => 'slo',
            'sl' => 'slv',
            'so' => 'som',
            'st' => 'sot',
            'es' => 'spa',
            'su' => 'sun',
            'sw' => 'swa',
            'ss' => 'ssw',
            'sv' => 'swe',
            'ta' => 'tam',
            'te' => 'tel',
            'tg' => 'tgk',
            'th' => 'tha',
            'ti' => 'tir',
            'bo' => 'tib',
            'tk' => 'tuk',
            'tl' => 'tgl',
            'tn' => 'tsn',
            'to' => 'ton',
            'tr' => 'tur',
            'ts' => 'tso',
            'tt' => 'tat',
            'tw' => 'twi',
            'ty' => 'tah',
            'ug' => 'uig',
            'uk' => 'ukr',
            'ur' => 'urd',
            'uz' => 'uzb',
            've' => 'ven',
            'vi' => 'vie',
            'vo' => 'vol',
            'wa' => 'wln',
            'cy' => 'wel',
            'wo' => 'wol',
            'fy' => 'fry',
            'xh' => 'xho',
            'yi' => 'yid',
            'yo' => 'yor',
            'za' => 'zha',
            'zu' => 'zul',
        ];
    }

    /**
     * @return array
     */
    private function iso3digit_T()
    {
        return [
            'abk' => 'ab',
            'aar' => 'aa',
            'afr' => 'af',
            'aka' => 'ak',
            'sqi' => 'sq',
            'amh' => 'am',
            'ara' => 'ar',
            'arg' => 'an',
            'hye' => 'hy',
            'asm' => 'as',
            'ava' => 'av',
            'ave' => 'ae',
            'aym' => 'ay',
            'aze' => 'az',
            'bam' => 'bm',
            'bak' => 'ba',
            'eus' => 'eu',
            'bel' => 'be',
            'ben' => 'bn',
            'bih' => 'bh',
            'bis' => 'bi',
            'bos' => 'bs',
            'bre' => 'br',
            'bul' => 'bg',
            'mya' => 'my',
            'cat' => 'ca',
            'cha' => 'ch',
            'che' => 'ce',
            'nya' => 'ny',
            'zho' => 'zh',
            'chv' => 'cv',
            'cor' => 'kw',
            'cos' => 'co',
            'cre' => 'cr',
            'hrv' => 'hr',
            'ces' => 'cs',
            'dan' => 'da',
            'div' => 'dv',
            'nld' => 'nl',
            'dzo' => 'dz',
            'eng' => 'en',
            'epo' => 'eo',
            'est' => 'et',
            'ewe' => 'ee',
            'fao' => 'fo',
            'fij' => 'fj',
            'fin' => 'fi',
            'fra' => 'fr',
            'ful' => 'ff',
            'glg' => 'gl',
            'kat' => 'ka',
            'deu' => 'de',
            'ell' => 'el',
            'grn' => 'gn',
            'guj' => 'gu',
            'hat' => 'ht',
            'hau' => 'ha',
            'heb' => 'he',
            'her' => 'hz',
            'hin' => 'hi',
            'hmo' => 'ho',
            'hun' => 'hu',
            'ina' => 'ia',
            'ind' => 'id',
            'ile' => 'ie',
            'gle' => 'ga',
            'ibo' => 'ig',
            'ipk' => 'ik',
            'ido' => 'io',
            'isl' => 'is',
            'ita' => 'it',
            'iku' => 'iu',
            'jpn' => 'ja',
            'jav' => 'jv',
            'kal' => 'kl',
            'kan' => 'kn',
            'kau' => 'kr',
            'kas' => 'ks',
            'kaz' => 'kk',
            'khm' => 'km',
            'kik' => 'ki',
            'kin' => 'rw',
            'kir' => 'ky',
            'kom' => 'kv',
            'kon' => 'kg',
            'kor' => 'ko',
            'kur' => 'ku',
            'kua' => 'kj',
            'lat' => 'la',
            'ltz' => 'lb',
            'lug' => 'lg',
            'lim' => 'li',
            'lin' => 'ln',
            'lao' => 'lo',
            'lit' => 'lt',
            'lub' => 'lu',
            'lav' => 'lv',
            'glv' => 'gv',
            'mkd' => 'mk',
            'mlg' => 'mg',
            'msa' => 'ms',
            'mal' => 'ml',
            'mlt' => 'mt',
            'mri' => 'mi',
            'mar' => 'mr',
            'mah' => 'mh',
            'mon' => 'mn',
            'nau' => 'na',
            'nav' => 'nv',
            'nde' => 'nd',
            'nep' => 'ne',
            'ndo' => 'ng',
            'nob' => 'nb',
            'nno' => 'nn',
            'nor' => 'no',
            'iii' => 'ii',
            'nbl' => 'nr',
            'oci' => 'oc',
            'oji' => 'oj',
            'chu' => 'cu',
            'orm' => 'om',
            'ori' => 'or',
            'oss' => 'os',
            'pan' => 'pa',
            'pli' => 'pi',
            'fas' => 'fa',
            'pol' => 'pl',
            'pus' => 'ps',
            'por' => 'pt',
            'que' => 'qu',
            'roh' => 'rm',
            'run' => 'rn',
            'ron' => 'ro',
            'rus' => 'ru',
            'san' => 'sa',
            'srd' => 'sc',
            'snd' => 'sd',
            'sme' => 'se',
            'smo' => 'sm',
            'sag' => 'sg',
            'srp' => 'sr',
            'gla' => 'gd',
            'sna' => 'sn',
            'sin' => 'si',
            'slk' => 'sk',
            'slv' => 'sl',
            'som' => 'so',
            'sot' => 'st',
            'spa' => 'es',
            'sun' => 'su',
            'swa' => 'sw',
            'ssw' => 'ss',
            'swe' => 'sv',
            'tam' => 'ta',
            'tel' => 'te',
            'tgk' => 'tg',
            'tha' => 'th',
            'tir' => 'ti',
            'bod' => 'bo',
            'tuk' => 'tk',
            'tgl' => 'tl',
            'tsn' => 'tn',
            'ton' => 'to',
            'tur' => 'tr',
            'tso' => 'ts',
            'tat' => 'tt',
            'twi' => 'tw',
            'tah' => 'ty',
            'uig' => 'ug',
            'ukr' => 'uk',
            'urd' => 'ur',
            'uzb' => 'uz',
            'ven' => 've',
            'vie' => 'vi',
            'vol' => 'vo',
            'wln' => 'wa',
            'cym' => 'cy',
            'wol' => 'wo',
            'fry' => 'fy',
            'xho' => 'xh',
            'yid' => 'yi',
            'yor' => 'yo',
            'zha' => 'za',
            'zul' => 'zu'
        ];
    }

    /**
     * @return array
     */
    private function iso3digit_B()
    {
        return [
            'abk' => 'ab',
            'aar' => 'aa',
            'afr' => 'af',
            'aka' => 'ak',
            'alb' => 'sq',
            'amh' => 'am',
            'ara' => 'ar',
            'arg' => 'an',
            'arm' => 'hy',
            'asm' => 'as',
            'ava' => 'av',
            'ave' => 'ae',
            'aym' => 'ay',
            'aze' => 'az',
            'bam' => 'bm',
            'bak' => 'ba',
            'baq' => 'eu',
            'bel' => 'be',
            'ben' => 'bn',
            'bih' => 'bh',
            'bis' => 'bi',
            'bos' => 'bs',
            'bre' => 'br',
            'bul' => 'bg',
            'bur' => 'my',
            'cat' => 'ca',
            'cha' => 'ch',
            'che' => 'ce',
            'nya' => 'ny',
            'chi' => 'zh',
            'chv' => 'cv',
            'cor' => 'kw',
            'cos' => 'co',
            'cre' => 'cr',
            'hrv' => 'hr',
            'cze' => 'cs',
            'dan' => 'da',
            'div' => 'dv',
            'dut' => 'nl',
            'dzo' => 'dz',
            'eng' => 'en',
            'epo' => 'eo',
            'est' => 'et',
            'ewe' => 'ee',
            'fao' => 'fo',
            'fij' => 'fj',
            'fin' => 'fi',
            'fre' => 'fr',
            'ful' => 'ff',
            'glg' => 'gl',
            'geo' => 'ka',
            'ger' => 'de',
            'gre' => 'el',
            'grn' => 'gn',
            'guj' => 'gu',
            'hat' => 'ht',
            'hau' => 'ha',
            'heb' => 'he',
            'her' => 'hz',
            'hin' => 'hi',
            'hmo' => 'ho',
            'hun' => 'hu',
            'ina' => 'ia',
            'ind' => 'id',
            'ile' => 'ie',
            'gle' => 'ga',
            'ibo' => 'ig',
            'ipk' => 'ik',
            'ido' => 'io',
            'ice' => 'is',
            'ita' => 'it',
            'iku' => 'iu',
            'jpn' => 'ja',
            'jav' => 'jv',
            'kal' => 'kl',
            'kan' => 'kn',
            'kau' => 'kr',
            'kas' => 'ks',
            'kaz' => 'kk',
            'khm' => 'km',
            'kik' => 'ki',
            'kin' => 'rw',
            'kir' => 'ky',
            'kom' => 'kv',
            'kon' => 'kg',
            'kor' => 'ko',
            'kur' => 'ku',
            'kua' => 'kj',
            'lat' => 'la',
            'ltz' => 'lb',
            'lug' => 'lg',
            'lim' => 'li',
            'lin' => 'ln',
            'lao' => 'lo',
            'lit' => 'lt',
            'lub' => 'lu',
            'lav' => 'lv',
            'glv' => 'gv',
            'mac' => 'mk',
            'mlg' => 'mg',
            'may' => 'ms',
            'mal' => 'ml',
            'mlt' => 'mt',
            'mao' => 'mi',
            'mar' => 'mr',
            'mah' => 'mh',
            'mon' => 'mn',
            'nau' => 'na',
            'nav' => 'nv',
            'nde' => 'nd',
            'nep' => 'ne',
            'ndo' => 'ng',
            'nob' => 'nb',
            'nno' => 'nn',
            'nor' => 'no',
            'iii' => 'ii',
            'nbl' => 'nr',
            'oci' => 'oc',
            'oji' => 'oj',
            'chu' => 'cu',
            'orm' => 'om',
            'ori' => 'or',
            'oss' => 'os',
            'pan' => 'pa',
            'pli' => 'pi',
            'per' => 'fa',
            'pol' => 'pl',
            'pus' => 'ps',
            'por' => 'pt',
            'que' => 'qu',
            'roh' => 'rm',
            'run' => 'rn',
            'rum' => 'ro',
            'rus' => 'ru',
            'san' => 'sa',
            'srd' => 'sc',
            'snd' => 'sd',
            'sme' => 'se',
            'smo' => 'sm',
            'sag' => 'sg',
            'srp' => 'sr',
            'gla' => 'gd',
            'sna' => 'sn',
            'sin' => 'si',
            'slo' => 'sk',
            'slv' => 'sl',
            'som' => 'so',
            'sot' => 'st',
            'spa' => 'es',
            'sun' => 'su',
            'swa' => 'sw',
            'ssw' => 'ss',
            'swe' => 'sv',
            'tam' => 'ta',
            'tel' => 'te',
            'tgk' => 'tg',
            'tha' => 'th',
            'tir' => 'ti',
            'tib' => 'bo',
            'tuk' => 'tk',
            'tgl' => 'tl',
            'tsn' => 'tn',
            'ton' => 'to',
            'tur' => 'tr',
            'tso' => 'ts',
            'tat' => 'tt',
            'twi' => 'tw',
            'tah' => 'ty',
            'uig' => 'ug',
            'ukr' => 'uk',
            'urd' => 'ur',
            'uzb' => 'uz',
            'ven' => 've',
            'vie' => 'vi',
            'vol' => 'vo',
            'wln' => 'wa',
            'wel' => 'cy',
            'wol' => 'wo',
            'fry' => 'fy',
            'xho' => 'xh',
            'yid' => 'yi',
            'yor' => 'yo',
            'zha' => 'za',
            'zul' => 'zu'
        ];
    }

    /**
     * @return array
     */
    private function alpha2digit()
    {
        return [
            'AF' => 'AFG',
            'AX' => 'ALA',
            'AL' => 'ALB',
            'DZ' => 'DZA',
            'AS' => 'ASM',
            'AD' => 'AND',
            'AO' => 'AGO',
            'AI' => 'AIA',
            'AQ' => 'ATA',
            'AG' => 'ATG',
            'AR' => 'ARG',
            'AM' => 'ARM',
            'AW' => 'ABW',
            'AU' => 'AUS',
            'AT' => 'AUT',
            'AZ' => 'AZE',
            'BS' => 'BHS',
            'BH' => 'BHR',
            'BD' => 'BGD',
            'BB' => 'BRB',
            'BY' => 'BLR',
            'BE' => 'BEL',
            'BZ' => 'BLZ',
            'BJ' => 'BEN',
            'BM' => 'BMU',
            'BT' => 'BTN',
            'BO' => 'BOL',
            'BA' => 'BIH',
            'BW' => 'BWA',
            'BV' => 'BVT',
            'BR' => 'BRA',
            'VG' => 'VGB',
            'IO' => 'IOT',
            'BN' => 'BRN',
            'BG' => 'BGR',
            'BF' => 'BFA',
            'BI' => 'BDI',
            'KH' => 'KHM',
            'CM' => 'CMR',
            'CA' => 'CAN',
            'CV' => 'CPV',
            'KY' => 'CYM',
            'CF' => 'CAF',
            'TD' => 'TCD',
            'CL' => 'CHL',
            'CN' => 'CHN',
            'HK' => 'HKG',
            'MO' => 'MAC',
            'CX' => 'CXR',
            'CC' => 'CCK',
            'CO' => 'COL',
            'KM' => 'COM',
            'CG' => 'COG',
            'CD' => 'COD',
            'CK' => 'COK',
            'CR' => 'CRI',
            'CI' => 'CIV',
            'HR' => 'HRV',
            'CU' => 'CUB',
            'CY' => 'CYP',
            'CZ' => 'CZE',
            'DK' => 'DNK',
            'DJ' => 'DJI',
            'DM' => 'DMA',
            'DO' => 'DOM',
            'EC' => 'ECU',
            'EG' => 'EGY',
            'SV' => 'SLV',
            'GQ' => 'GNQ',
            'ER' => 'ERI',
            'EE' => 'EST',
            'ET' => 'ETH',
            'FK' => 'FLK',
            'FO' => 'FRO',
            'FJ' => 'FJI',
            'FI' => 'FIN',
            'FR' => 'FRA',
            'GF' => 'GUF',
            'PF' => 'PYF',
            'TF' => 'ATF',
            'GA' => 'GAB',
            'GM' => 'GMB',
            'GE' => 'GEO',
            'DE' => 'DEU',
            'GH' => 'GHA',
            'GI' => 'GIB',
            'GR' => 'GRC',
            'GL' => 'GRL',
            'GD' => 'GRD',
            'GP' => 'GLP',
            'GU' => 'GUM',
            'GT' => 'GTM',
            'GG' => 'GGY',
            'GN' => 'GIN',
            'GW' => 'GNB',
            'GY' => 'GUY',
            'HT' => 'HTI',
            'HM' => 'HMD',
            'VA' => 'VAT',
            'HN' => 'HND',
            'HU' => 'HUN',
            'IS' => 'ISL',
            'IN' => 'IND',
            'ID' => 'IDN',
            'IR' => 'IRN',
            'IQ' => 'IRQ',
            'IE' => 'IRL',
            'IM' => 'IMN',
            'IL' => 'ISR',
            'IT' => 'ITA',
            'JM' => 'JAM',
            'JP' => 'JPN',
            'JE' => 'JEY',
            'JO' => 'JOR',
            'KZ' => 'KAZ',
            'KE' => 'KEN',
            'KI' => 'KIR',
            'KP' => 'PRK',
            'KR' => 'KOR',
            'KW' => 'KWT',
            'KG' => 'KGZ',
            'LA' => 'LAO',
            'LV' => 'LVA',
            'LB' => 'LBN',
            'LS' => 'LSO',
            'LR' => 'LBR',
            'LY' => 'LBY',
            'LI' => 'LIE',
            'LT' => 'LTU',
            'LU' => 'LUX',
            'MK' => 'MKD',
            'MG' => 'MDG',
            'MW' => 'MWI',
            'MY' => 'MYS',
            'MV' => 'MDV',
            'ML' => 'MLI',
            'MT' => 'MLT',
            'MH' => 'MHL',
            'MQ' => 'MTQ',
            'MR' => 'MRT',
            'MU' => 'MUS',
            'YT' => 'MYT',
            'MX' => 'MEX',
            'FM' => 'FSM',
            'MD' => 'MDA',
            'MC' => 'MCO',
            'MN' => 'MNG',
            'ME' => 'MNE',
            'MS' => 'MSR',
            'MA' => 'MAR',
            'MZ' => 'MOZ',
            'MM' => 'MMR',
            'NA' => 'NAM',
            'NR' => 'NRU',
            'NP' => 'NPL',
            'NL' => 'NLD',
            'AN' => 'ANT',
            'NC' => 'NCL',
            'NZ' => 'NZL',
            'NI' => 'NIC',
            'NE' => 'NER',
            'NG' => 'NGA',
            'NU' => 'NIU',
            'NF' => 'NFK',
            'MP' => 'MNP',
            'NO' => 'NOR',
            'OM' => 'OMN',
            'PK' => 'PAK',
            'PW' => 'PLW',
            'PS' => 'PSE',
            'PA' => 'PAN',
            'PG' => 'PNG',
            'PY' => 'PRY',
            'PE' => 'PER',
            'PH' => 'PHL',
            'PN' => 'PCN',
            'PL' => 'POL',
            'PT' => 'PRT',
            'PR' => 'PRI',
            'QA' => 'QAT',
            'RE' => 'REU',
            'RO' => 'ROU',
            'RU' => 'RUS',
            'RW' => 'RWA',
            'BL' => 'BLM',
            'SH' => 'SHN',
            'KN' => 'KNA',
            'LC' => 'LCA',
            'MF' => 'MAF',
            'PM' => 'SPM',
            'VC' => 'VCT',
            'WS' => 'WSM',
            'SM' => 'SMR',
            'ST' => 'STP',
            'SA' => 'SAU',
            'SN' => 'SEN',
            'RS' => 'SRB',
            'SC' => 'SYC',
            'SL' => 'SLE',
            'SG' => 'SGP',
            'SK' => 'SVK',
            'SI' => 'SVN',
            'SB' => 'SLB',
            'SO' => 'SOM',
            'ZA' => 'ZAF',
            'GS' => 'SGS',
            'SS' => 'SSD',
            'ES' => 'ESP',
            'LK' => 'LKA',
            'SD' => 'SDN',
            'SR' => 'SUR',
            'SJ' => 'SJM',
            'SZ' => 'SWZ',
            'SE' => 'SWE',
            'CH' => 'CHE',
            'SY' => 'SYR',
            'TW' => 'TWN',
            'TJ' => 'TJK',
            'TZ' => 'TZA',
            'TH' => 'THA',
            'TL' => 'TLS',
            'TG' => 'TGO',
            'TK' => 'TKL',
            'TO' => 'TON',
            'TT' => 'TTO',
            'TN' => 'TUN',
            'TR' => 'TUR',
            'TM' => 'TKM',
            'TC' => 'TCA',
            'TV' => 'TUV',
            'UG' => 'UGA',
            'UA' => 'UKR',
            'AE' => 'ARE',
            'GB' => 'GBR',
            'US' => 'USA',
            'UM' => 'UMI',
            'UY' => 'URY',
            'UZ' => 'UZB',
            'VU' => 'VUT',
            'VE' => 'VEN',
            'VN' => 'VNM',
            'VI' => 'VIR',
            'WF' => 'WLF',
            'EH' => 'ESH',
            'YE' => 'YEM',
            'ZM' => 'ZMB',
            'ZW' => 'ZWE'
        ];
    }

    /**
     * @return array
     */
    private function alpha3digit()
    {
        return [
            'AFG' => 'AF',
            'ALA' => 'AX',
            'ALB' => 'AL',
            'DZA' => 'DZ',
            'ASM' => 'AS',
            'AND' => 'AD',
            'AGO' => 'AO',
            'AIA' => 'AI',
            'ATA' => 'AQ',
            'ATG' => 'AG',
            'ARG' => 'AR',
            'ARM' => 'AM',
            'ABW' => 'AW',
            'AUS' => 'AU',
            'AUT' => 'AT',
            'AZE' => 'AZ',
            'BHS' => 'BS',
            'BHR' => 'BH',
            'BGD' => 'BD',
            'BRB' => 'BB',
            'BLR' => 'BY',
            'BEL' => 'BE',
            'BLZ' => 'BZ',
            'BEN' => 'BJ',
            'BMU' => 'BM',
            'BTN' => 'BT',
            'BOL' => 'BO',
            'BIH' => 'BA',
            'BWA' => 'BW',
            'BVT' => 'BV',
            'BRA' => 'BR',
            'VGB' => 'VG',
            'IOT' => 'IO',
            'BRN' => 'BN',
            'BGR' => 'BG',
            'BFA' => 'BF',
            'BDI' => 'BI',
            'KHM' => 'KH',
            'CMR' => 'CM',
            'CAN' => 'CA',
            'CPV' => 'CV',
            'CYM' => 'KY',
            'CAF' => 'CF',
            'TCD' => 'TD',
            'CHL' => 'CL',
            'CHN' => 'CN',
            'HKG' => 'HK',
            'MAC' => 'MO',
            'CXR' => 'CX',
            'CCK' => 'CC',
            'COL' => 'CO',
            'COM' => 'KM',
            'COG' => 'CG',
            'COD' => 'CD',
            'COK' => 'CK',
            'CRI' => 'CR',
            'CIV' => 'CI',
            'HRV' => 'HR',
            'CUB' => 'CU',
            'CYP' => 'CY',
            'CZE' => 'CZ',
            'DNK' => 'DK',
            'DJI' => 'DJ',
            'DMA' => 'DM',
            'DOM' => 'DO',
            'ECU' => 'EC',
            'EGY' => 'EG',
            'SLV' => 'SV',
            'GNQ' => 'GQ',
            'ERI' => 'ER',
            'EST' => 'EE',
            'ETH' => 'ET',
            'FLK' => 'FK',
            'FRO' => 'FO',
            'FJI' => 'FJ',
            'FIN' => 'FI',
            'FRA' => 'FR',
            'GUF' => 'GF',
            'PYF' => 'PF',
            'ATF' => 'TF',
            'GAB' => 'GA',
            'GMB' => 'GM',
            'GEO' => 'GE',
            'DEU' => 'DE',
            'GHA' => 'GH',
            'GIB' => 'GI',
            'GRC' => 'GR',
            'GRL' => 'GL',
            'GRD' => 'GD',
            'GLP' => 'GP',
            'GUM' => 'GU',
            'GTM' => 'GT',
            'GGY' => 'GG',
            'GIN' => 'GN',
            'GNB' => 'GW',
            'GUY' => 'GY',
            'HTI' => 'HT',
            'HMD' => 'HM',
            'VAT' => 'VA',
            'HND' => 'HN',
            'HUN' => 'HU',
            'ISL' => 'IS',
            'IND' => 'IN',
            'IDN' => 'ID',
            'IRN' => 'IR',
            'IRQ' => 'IQ',
            'IRL' => 'IE',
            'IMN' => 'IM',
            'ISR' => 'IL',
            'ITA' => 'IT',
            'JAM' => 'JM',
            'JPN' => 'JP',
            'JEY' => 'JE',
            'JOR' => 'JO',
            'KAZ' => 'KZ',
            'KEN' => 'KE',
            'KIR' => 'KI',
            'PRK' => 'KP',
            'KOR' => 'KR',
            'KWT' => 'KW',
            'KGZ' => 'KG',
            'LAO' => 'LA',
            'LVA' => 'LV',
            'LBN' => 'LB',
            'LSO' => 'LS',
            'LBR' => 'LR',
            'LBY' => 'LY',
            'LIE' => 'LI',
            'LTU' => 'LT',
            'LUX' => 'LU',
            'MKD' => 'MK',
            'MDG' => 'MG',
            'MWI' => 'MW',
            'MYS' => 'MY',
            'MDV' => 'MV',
            'MLI' => 'ML',
            'MLT' => 'MT',
            'MHL' => 'MH',
            'MTQ' => 'MQ',
            'MRT' => 'MR',
            'MUS' => 'MU',
            'MYT' => 'YT',
            'MEX' => 'MX',
            'FSM' => 'FM',
            'MDA' => 'MD',
            'MCO' => 'MC',
            'MNG' => 'MN',
            'MNE' => 'ME',
            'MSR' => 'MS',
            'MAR' => 'MA',
            'MOZ' => 'MZ',
            'MMR' => 'MM',
            'NAM' => 'NA',
            'NRU' => 'NR',
            'NPL' => 'NP',
            'NLD' => 'NL',
            'ANT' => 'AN',
            'NCL' => 'NC',
            'NZL' => 'NZ',
            'NIC' => 'NI',
            'NER' => 'NE',
            'NGA' => 'NG',
            'NIU' => 'NU',
            'NFK' => 'NF',
            'MNP' => 'MP',
            'NOR' => 'NO',
            'OMN' => 'OM',
            'PAK' => 'PK',
            'PLW' => 'PW',
            'PSE' => 'PS',
            'PAN' => 'PA',
            'PNG' => 'PG',
            'PRY' => 'PY',
            'PER' => 'PE',
            'PHL' => 'PH',
            'PCN' => 'PN',
            'POL' => 'PL',
            'PRT' => 'PT',
            'PRI' => 'PR',
            'QAT' => 'QA',
            'REU' => 'RE',
            'ROU' => 'RO',
            'RUS' => 'RU',
            'RWA' => 'RW',
            'BLM' => 'BL',
            'SHN' => 'SH',
            'KNA' => 'KN',
            'LCA' => 'LC',
            'MAF' => 'MF',
            'SPM' => 'PM',
            'VCT' => 'VC',
            'WSM' => 'WS',
            'SMR' => 'SM',
            'STP' => 'ST',
            'SAU' => 'SA',
            'SEN' => 'SN',
            'SRB' => 'RS',
            'SYC' => 'SC',
            'SLE' => 'SL',
            'SGP' => 'SG',
            'SVK' => 'SK',
            'SVN' => 'SI',
            'SLB' => 'SB',
            'SOM' => 'SO',
            'ZAF' => 'ZA',
            'SGS' => 'GS',
            'SSD' => 'SS',
            'ESP' => 'ES',
            'LKA' => 'LK',
            'SDN' => 'SD',
            'SUR' => 'SR',
            'SJM' => 'SJ',
            'SWZ' => 'SZ',
            'SWE' => 'SE',
            'CHE' => 'CH',
            'SYR' => 'SY',
            'TWN' => 'TW',
            'TJK' => 'TJ',
            'TZA' => 'TZ',
            'THA' => 'TH',
            'TLS' => 'TL',
            'TGO' => 'TG',
            'TKL' => 'TK',
            'TON' => 'TO',
            'TTO' => 'TT',
            'TUN' => 'TN',
            'TUR' => 'TR',
            'TKM' => 'TM',
            'TCA' => 'TC',
            'TUV' => 'TV',
            'UGA' => 'UG',
            'UKR' => 'UA',
            'ARE' => 'AE',
            'GBR' => 'GB',
            'USA' => 'US',
            'UMI' => 'UM',
            'URY' => 'UY',
            'UZB' => 'UZ',
            'VUT' => 'VU',
            'VEN' => 'VE',
            'VNM' => 'VN',
            'VIR' => 'VI',
            'WLF' => 'WF',
            'ESH' => 'EH',
            'YEM' => 'YE',
            'ZMB' => 'ZM',
            'ZWE' => 'ZW'
        ];
    }
}
?>
